use customer ; 
SELECT * FROM customer_detail;
    
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , SUM(purchase_amount) as revenue
from customer_detail 
group by gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, discount_applied, gender, purchase_amount
FROM customer_detail
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM customer_detail
);
 
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, 
       round(AVG(review_rating) , 2) AS avg_rating,
       COUNT(*) AS total_reviews
FROM customer_detail
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, avg(purchase_amount) as avg_amount 
from customer_detail
where shipping_type In ("Standard" , "Express") 
group by shipping_type  ;


-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status , 
COUNT(customer_id) as total_costomer,
AVG(purchase_amount) as avg_spend , 
SUM(purchase_amount) as total_revenue 
from customer_detail
group by subscription_status 
order by total_revenue  , avg_spend desc ; 


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select  item_purchased ,
100*SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0  END)/COUNT(*)  as discount_rate 
from customer_detail 
group by item_purchased 
order by discount_rate desc 
limit 5 ;  
 
-- Q7. Segment customers into New, Returning, 
-- and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id , previous_purchases  ,
CASE
    WHEN previous_purchases = 1 THEN 'New' 
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returing'
    ELSE 'Loyal' 
    END AS customer_segment 
from customer_detail 
)

SELECT customer_segment , COUNT(*) as "Number of customer" 
from customer_type 
group by customer_segment ;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS ( 
    SELECT 
        category, 
        item_purchased, 
        COUNT(customer_id) AS total_orders, 
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank 
    FROM customer_detail
    GROUP BY category, item_purchased 
) 

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts 
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status , 
count(customer_id) as repeat_buyers
from customer_detail 
where previous_purchases > 5
group by subscription_status ;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group , 
SUM(purchase_amount) as total_revenue 
from customer_detail
group by age_group 
order by total_revenue desc ; 






















































































































